### ISSUE TITLE
[TRACKING] Issues with Foretold estimate distributions and consistency

### ISSUE THREAD

**Issue by wolverdude** [epidemics/covid#215]
Why are some of the estimates lower than the confirmed cases? I take it `FT_Infected` is active whereas `JH_Confirmed` is cumulative?

If so, we should either make it clear that these numbers measure different things or do the math to make confirmed into "confirmed active cases"?

<img width="416" alt="Screen Shot 2020-03-20 at 5 31 31 PM" src="https://user-images.githubusercontent.com/4276302/77215403-0ef70400-6ad1-11ea-85be-18e6a3d71040.png">

```json
{
  "JH_Deaths": 0,
  "JH_Confirmed": 226,
  "JH_Recovered": 105,
  "JH_Infected": 0,
  "FT_Infected": 190,
  "FT_Infected_q05": 48,
  "FT_Infected_q95": 590
}
```

**Comment by lagerros** [comment]
Correct, JH is cumulative and FT is active. We could change text to "Total confirmed" and "Estimated active". 

(I'll do it later unless you've already done it then.)

**Comment by wolverdude** [comment]
I think it makes more sense to change the section title to *Current Active Infections* and then compute *Confirmed* as `JH_Confirmed - JH_Recovered  - JH_Deaths`.

**Comment by lagerros** [comment]
Ah, that's just so much better. Go for it

**Comment by wolverdude** [comment]
Okay, that should be fixed with this PR. That said, there's still the funny business that the lower bound of the 90% CI is below, no _waaay_ below the number of actual, confirmed cases that are still ongoing. Is this because the model takes into account that many who haven't yet been reported as recovered have actually recovered already?

**Comment by gavento** [comment]
> I think it makes more sense to change the section title to **Current Active Infections** and then compute **Confirmed** as `JH_Confirmed - JH_Recovered - JH_Deaths`.

That number was supposed be in `JH_Infected` in the JSON, but it is now filled with zeros. (Was generated manually).

Thanks for fixing this!

**Comment by gavento** [comment]
> Okay, that should be fixed with this PR. That said, there's still the funny business that the lower bound of the 90% CI is below, no _waaay_ below the number of actual, confirmed cases that are still ongoing. Is this because the model takes into account that many who haven't yet been reported as recovered have actually recovered already?

Hmm, that is likely an artifact of Foretold - forecasters give estimates and variance (indirectly) and this can easily have this effect with the default distributions (I am surprised we don't see some negative numbers there :grin: ). It would make sense to somewhat lower bound the estimates by JH (as all the forecasters likely do) and take it into account inside Foretold ... Not sure what a correct way to do it would be. @OAGr ?

But I would suggest just to bound the CI lower bound by JH Active from below for now. @lagerros @wolverdude

**Comment by gavento** [comment]
Thanks for the PR, but it does not solve the issue of FT lower bound being smaller.

Could you please also fix this @wolverdude? (e.g. show our estimate lower bound to be at least the JH active number).

**Comment by OAGr** [comment]
I'm working on a fix that should be set up in the next 2-8 days. How urgent is this now?

**Comment by gavento** [comment]
@OAGr I don't think it is very urgent if you think the obvious quickfix of cutting the distribution off at the John Hopkins currently confirmed active does not distort it much for
1. display (likely not)
2. regression / nowcasting
  * I would still tend to use the original mean when just that is needed - as this is something people usually input. Woud you agree?

**Comment by OAGr** [comment]
Hm... the mean isn't actually that correct in these cases. In the cases where the numbers look really weird, it's because the range was higher than the system could handle (it could only handle maybe 1-2 orders of magnitude). I'll think about this, will try do something quick on Monday/Tuesday.

**Comment by OAGr** [comment]
I've been working on a slightly more advanced Kernel Density Estimation system here:
https://www.highlyspeculativeestimates.com/dist-builder. If we could spend 1-4min per estimate-that-needs-fixing we could fix them manually using that, basically, though this of course would take some time.

**Comment by gavento** [comment]
I would rather wait for a systematic solution, unless you'd think that the error is more than ~50%.

Which means do you mean? I compute them from the distribution returned by GraphQL (does not give the mean) and it roughly matched the mean shown in Foretold (although with even ~20% difference).

**Comment by OAGr** [comment]
I'd expect that many of the distributions returned from GraphQL would have deviations; of which the mean is wrong by over 50%.

**Comment by OAGr** [comment]
This one for example:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/377065/77250183-0e2fb080-6c3e-11ea-9bb4-bc8fc3921042.png">

**Comment by OAGr** [comment]
Meanwhile, I'd expect this one to be mostly fine:
<img width="86" alt="image" src="https://user-images.githubusercontent.com/377065/77250195-2273ad80-6c3e-11ea-93d5-231b51f3a3f7.png">

**Comment by OAGr** [comment]
Would it help much if the API could give you the means directly? I realize this is less important.

**Comment by lagerros** [comment]
If the API could provide summary statistics directly (mean, 90% CI) that would be *very* useful to us!

**Comment by gavento** [comment]
@lagerros I think sorting out the wide distributions and aggregation is higher priority (and required for this anyway?)
We have the full distribution loaded [here](https://github.com/epidemics/epifor/blob/b3f19a55fb2f4c27a13ac367477fb4988fb02b8e/epifor/data/foretold.py#L36), means are computed, quantiles with numpy are straightforward once the data is there.

Definitely in favor if it would be for any reason more robust or faster to do on Foretold side.

**Comment by lagerros** [comment]
I didn't know you were actually doing that in numpy!

@OAGr I change my mind, I was wrong, summary statistics isn't very useful. Personally would have found it somewhat useful, but agree with @gavento messages

**Comment by wolverdude** [comment]
Do we still want a stopgap fix on the frontend for this?

**Comment by hnykda** [comment]
No idea. It's unclear to me what the goal is (the ticket doesn't tell what to do), so I am going to move it `To do` and label with `need-clarification`.

**Comment by gavento** [comment]
We are currently not using foretold at all. This is more of a progress tracking issue that an actionable one.

**Comment by hnykda** [comment]
created a label for it

Does it have to be at the board though?

**Comment by hnykda** [comment]
I am not sure what the resolution would be here, closing it.

**Comment by OAGr** [comment]
Btw, I've implemented the relevant fix on Foretold, so at least distributions should show up correctly on Foretold now.
